import Header from '../components/Header.jsx'
import { Providers } from '../components/Provider';

import Footer_common from "../components/Footer_common.jsx"
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className=" ">
        <Providers>
          <Header/>
          {children}
          <Footer_common />
        </Providers>
      </body>
    </html>
  )
}
